export const ResponseMessage={
    INTERNAL_SERVER:"Internal server error",
    CREATE_USER:"Registration successfully",
    USER_UPDATED:"User profile updated successfully",
    USER_NOT_FOUND:"User not found",
    USER_LIST:"User list fetched successfully",
    USER_DELETE:"User deleted successfully",
    EMAIL_ALREADY_EXIST:"Email already exist",
    MOBILE_ALREADY_EXIST:"Mobile number already exist",
    INVALID_CREDENTIAL:"Invalid credential",
    USER_LOGIN:"Logged in successfully",
    TOKEN_NOTAUTHORIZES:"Token not authorized",
    OTP_SEND:'OTP send on your email address',
    REQUEST_SEND_SUCCESSFULLY:"Request send successfully",
    CONVERSATION_ROOM_NOT_FOUND:"Conversation room not found",
    REQUEST_ACCEPT_SUCCESSFULLY:'Request accept successfully',
    CONVERSATION_ROOM_FETCHED:"Conversation room fetched successfully",
   CHAT_FETCHED_FETCHED:"Chat fetched successfully",
    CHAT_NOT_FOUND:" Chat not found",
    CHAT_SAVED_SUCCESSFULLY:"Chat saved successfully",
    ROOM_JOIN_SUCCESSFULLY:"Room joined successfully",
    ROOM_ALREADY_JOINED:"Room already joined successfully",
}